package com.blog.beans;
// default package
// Generated 2017-7-21 23:35:03 by Hibernate Tools 5.2.3.Final

/**
 * BlogJoinLabel generated by hbm2java
 */
public class BlogJoinLabel implements java.io.Serializable {

	private Integer id;
	private Integer blogId;
	private Integer labelId;

	public BlogJoinLabel() {
	}

	public BlogJoinLabel(Integer blogId, Integer labelId) {
		this.blogId = blogId;
		this.labelId = labelId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBlogId() {
		return this.blogId;
	}

	public void setBlogId(Integer blogId) {
		this.blogId = blogId;
	}

	public Integer getLabelId() {
		return this.labelId;
	}

	public void setLabelId(Integer labelId) {
		this.labelId = labelId;
	}

}
